server.port=${PORT:8080}
spring.main.banner-mode=off
# Graceful shutdown config for production
server.shutdown=graceful

# Developer metadata (Configurable via Environment Variables on Render)
bfhl.user-id=${BFHL_USER_ID:jayant_chugh_21122004}
bfhl.email=${BFHL_EMAIL:jayant0450.be23@chitkara.edu.in}
bfhl.roll-number=${BFHL_ROLL_NUMBER:2310990450}

